### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by benjspriggs** [benjspriggs/iron#19]
Iron needs a logo!

**Comment by benjspriggs** [comment]
Could look at a [logo like this one](https://www.flaticon.com/free-icon/iron_966991#term=iron&page=1&position=12), or any [listed here](https://www.flaticon.com/search?word=iron).

**Comment by richardbmx** [comment]
@benjspriggs  Hello I am a graphic designer and I like to make contributions to projects on github, I see that they are looking for a logo if you authorize me and tell me what the app is about and how you would like a logo, with pleasure I can make one ... regards ..

**Comment by richardbmx** [comment]
I present a proposal based on the images that you put if you like some we can develop it in different variations

![logotipo89s5propuesta](https://user-images.githubusercontent.com/35604837/42355276-279983d4-809a-11e8-961f-5ca270d66f5d.png)

**Comment by benjspriggs** [comment]
Perfect @richardbmx, thanks for the contributions! I'll make sure to add credits when the logo is included.

**Comment by richardbmx** [comment]
@benjspriggs How good that you like it ... I would like to know which of all you liked to make a google folder with the different files so you can use it

**Comment by benjspriggs** [comment]
@richardbmx The red with yellow highlighted iron caught my eye first.

**Comment by richardbmx** [comment]
@benjspriggs  I'm going to make a google folder with all the files that you can use it

**Comment by richardbmx** [comment]
Here you can find all the necessary files for the use of the logo are incorporated different variations of it and its original editable source files so you can modify it and use it wherever you want

Google Drive Folder
[All File](https://drive.google.com/open?id=154ORzvkdl4_18p0yX1o39qIvnQMTyC9l)

**Comment by benjspriggs** [comment]
Thanks a bunch, your help is very much appreciated!

**Comment by richardbmx** [comment]
@benjspriggs  Excellent if you want some change do not hesitate to say it
